# Dependencies
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/apt'

# SSH
mod 'saz/ssh'

# Nginx
mod 'rehan/nginx'

# GIT
mod 'puppetlabs/git'

# PHP
mod 'mayflower/php',
  :git => 'https://github.com/mayflower/puppet-php'

# Mysql
mod 'puppetlabs/mysql','3.8.0'

# Ruby
mod 'camptocamp/ruby'
mod 'camptocamp/buildenv'

#Node.js and NPM
mod 'willdurand/nodejs'
